---
- name: "Upgrading APT packages to latest version"
  hosts: myself
  
  tasks:
  
  - name: "Asking remote become password"
    pause:
      prompt: "Password:"
      echo: false
    register: become_password
  
  - name: "Searching and installing new pkgs upgrades"
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      name: "*"
      state: latest
    become: true
    vars:
      ansible_become_password: "{{ become_password.user_input }}"
    register: result

  - name: "Removing onpenssh-server package"
    ansible.builtin.apt:
      name: "openssh-server"
      state: absent
    become: true
    vars: 
      ansible_becom_password: "{{ become_password.user_input }}"
    register: result

  - debug:
      var: result.stdout
