---
- name: "Upgrading all APT-based packages to latest version and installing or removing specific pkg"
  hosts: myself
  vars:
    pkg_status: "absent" # absent to remove a pkg / present to install a pkg
    pkg_name: "openssh-server" # name pkg to install
    skip_inst_or_rm: true # true if you want to skip installation/removing specific pkg task or false to run it
  
  tasks:
  
  - name: "Asking remote become password"
    pause:
      prompt: "Password:"
      echo: false
    register: become_password
  
  - name: "Searching and installing new pkgs upgrades"
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      name: "*"
      state: latest
    become: true
    vars:
      ansible_become_password: "{{ become_password.user_input }}"
        #register: result

  - name: "{{ 'Installing ' if pkg_status == 'present' else ( 'Removing ' if pkg_status == 'absent' else 'pkg_status wrong status for ' )}}{{ pkg_name }} package"
    ansible.builtin.apt:
      name: "{{ pkg_name }}"
      state: "{{ pkg_status }}" 
    become: true
    vars: 
      ansible_becom_password: "{{ become_password.user_input }}"
        #register: result
    when: not skip_inst_or_rm

        #- debug:
        #var: result.stdout
