---
- name: "Upgrading APT packages to latest version"
  hosts: myself
  vars:
    pkg_status: "absent" # absent to remove a pkg / present to install a pkg
    pkg_name: "openssh-server" # name pkg to install
  
  tasks:
  
  - name: "Asking remote become password"
    pause:
      prompt: "Password:"
      echo: false
    register: become_password
  
  - name: "Searching and installing new pkgs upgrades"
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      name: "*"
      state: latest
    become: true
    vars:
      ansible_become_password: "{{ become_password.user_input }}"
        #register: result

  - name: "{{ 'Installing ' if pkg_status == 'present' }}{{ 'Removing ' if pkg_status == 'absent' }}{{ pkg_name }} package"
    ansible.builtin.apt:
      name: "{{ pkg_name }}"
      state: "{{ pkg_status }}" 
    become: true
    vars: 
      ansible_becom_password: "{{ become_password.user_input }}"
        #register: result

        #- debug:
        #var: result.stdout
